name: Wheels

on:
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    name: Run Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Clang
        run: sudo apt-get install -y clang

      - name: Set environment variables for Clang
        run: |
          export CC=$(which clang)
          export CXX=$(which clang++)
          

      - run: |
          cd package
          ./get_sources
          pip install .
          pip install pytest
          nucleofind-install --all 
          pytest tests

  debug:
      needs: [run_tests]
      runs-on: ubuntu-latest
      if: ${{ failure() }}
      steps:
        - uses: actions/checkout@v3
        - name: Notify chat
          uses: teknatha136/actions-google-chat-text-message@main
          with:
            google-chat-webhook: ${{ secrets.WEBHOOK_URL }}
            text-message: ${{ github.actor }} attempted to merge a change into NucleoFind, but this PR failed testing. Link ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \n