name: Wheels

on:
  pull_request:
    branches:
      - master

jobs:
  check_versioning:
    name: Check versions match
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          cd package
          ./get_sources
          pip install . 
          python tests/test_version.py -version ${{ github.event.release.tag_name }}

  run_tests:
    name: Run Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          cd package
          ./get_sources
          pip install .
          pip install pytest
          nucleofind-install -m all 
          pytest tests

  debug:
      needs: [check_versioning, run_tests]
      runs-on: ubuntu-latest
      if: ${{ failure() }}
      steps:
        - uses: actions/checkout@v3
        - name: Notify chat
          uses: teknatha136/actions-google-chat-text-message@main
          with:
            google-chat-webhook: ${{ secrets.WEBHOOK_URL }}
            text-message: ${{ github.actor }} attempted to merge a change into NucleoFind, but this PR failed testing. Link ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \n