name: Wheels

on:
  workflow_dispatch:
  pull_request:
    branches:
     - master
  push:
    branches:
      - build-support
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[Skip CI]')"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Move to correct directory
      run: |
        mv package/* . 
        ./get_sources

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v4
      with:
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[Skip CI]')"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Download dependencies
      run:  |
        cd package
        ./get_sources

    - uses: pypa/cibuildwheel@v2.16
      env:
        CIBW_BEFORE_ALL: pwd && ls
        # Cross-compile on macOS
        CIBW_ARCHS_MACOS: x86_64 arm64

        # Temporary: use pre-release Python 3.12 for stable ABI builds
        CIBW_PRERELEASE_PYTHONS: True
      with:
        package-dir: 'package'
        config-file: "{package}/pyproject.toml"

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*.whl
        name: dist-${{ matrix.os }}


  upload_all:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/setup-python@v5

    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true
        pattern: dist-*
        path: dist

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}