name: Publish release

on: 
  release:
    types: [published]

jobs:
  build:
    name: Build distribution 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Build and Deploy
      run: |
        cd package
        pip install setuptools twine
        python3 setup.py sdist
        twine upload dist/* -u ${{secrets.TWINE_USER}} -p ${{secrets.TWINE_PASS}}
